export const menu = {
  menu: [
    {
      _id: "1",
      name: "Paneer Butter Masala",
      price: 320,
      description: "Soft paneer cubes cooked in a rich, creamy tomato gravy.",
      ingredients: ["Paneer", "Tomato", "Butter", "Cream", "Spices"],
      rating: 4.6,
      category: "Curry",
      image: "paneer_butter_masala.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Amazing flavor!", "Perfect with naan."],
    },
    {
      _id: "2",
      name: "Chicken Biryani",
      price: 450,
      description: "Aromatic rice dish with marinated chicken and spices.",
      ingredients: ["Basmati Rice", "Chicken", "Spices", "Yogurt"],
      rating: 4.8,
      category: "Biryani",
      image: "chicken_biryani.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": ["Best biryani ever!", "Very flavorful and filling."],
    },
    {
      _id: "3",
      name: "Dal Makhani",
      price: 280,
      description: "Slow-cooked black lentils with butter and cream.",
      ingredients: ["Black Lentils", "Butter", "Cream", "Tomatoes", "Spices"],
      rating: 4.7,
      category: "Curry",
      image: "dal_makhani.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Rich and creamy!", "Tastes amazing with naan."],
    },
    {
      _id: "4",
      name: "Tandoori Chicken",
      price: 520,
      description:
        "Chicken marinated in yogurt and spices, grilled in a tandoor.",
      ingredients: ["Chicken", "Yogurt", "Spices", "Lemon", "Garlic"],
      rating: 4.9,
      category: "Tandoori",
      image: "tandoori_chicken.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": ["Juicy and flavorful!", "Perfectly cooked."],
    },
    {
      _id: "5",
      name: "Aloo Paratha",
      price: 120,
      description: "Whole wheat bread stuffed with spiced mashed potatoes.",
      ingredients: ["Wheat Flour", "Potatoes", "Spices", "Butter"],
      rating: 4.6,
      category: "Bread",
      image: "aloo_paratha.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Perfect breakfast!", "Delicious with curd."],
    },
    {
      _id: "6",
      name: "Chole Bhature",
      price: 180,
      description: "Spiced chickpea curry served with deep-fried bread.",
      ingredients: ["Chickpeas", "Tomatoes", "Flour", "Spices"],
      rating: 4.7,
      category: "North Indian",
      image: "chole_bhature.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Spicy and delicious!", "Bhature was crispy."],
    },
    {
      _id: "7",
      name: "Masala Dosa",
      price: 150,
      description:
        "Crispy fermented rice crepe filled with spicy potato mixture.",
      ingredients: ["Rice", "Lentils", "Potatoes", "Spices"],
      rating: 4.8,
      category: "South Indian",
      image: "masala_dosa.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Crispy and tasty!", "Sambar was perfect."],
    },
    {
      _id: "8",
      name: "Mutton Rogan Josh",
      price: 580,
      description: "Slow-cooked mutton curry with aromatic Kashmiri spices.",
      ingredients: ["Mutton", "Yogurt", "Onions", "Spices"],
      rating: 4.9,
      category: "Curry",
      image: "mutton_rogan_josh.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": ["Rich and flavorful!", "Authentic Kashmiri taste."],
    },
    {
      _id: "9",
      name: "Hyderabadi Dum Biryani",
      price: 560,
      description:
        "Fragrant basmati rice cooked with marinated mutton and saffron.",
      ingredients: ["Basmati Rice", "Mutton", "Yogurt", "Spices"],
      rating: 4.9,
      category: "Biryani",
      image: "hyderabadi_dum_biryani.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": [
        "Authentic and flavorful!",
        "Perfect spice balance.",
      ],
    },
    {
      _id: "10",
      name: "Rajma Chawal",
      price: 250,
      description: "Kidney beans cooked in tomato gravy, served with rice.",
      ingredients: ["Kidney Beans", "Tomatoes", "Rice", "Spices"],
      rating: 4.7,
      category: "North Indian",
      image: "rajma_chawal.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Comfort food!", "Tastes like home-cooked meal."],
    },
    {
      _id: "11",
      name: "Samosa",
      price: 40,
      description: "Crispy fried pastry filled with spiced potatoes and peas.",
      ingredients: ["Flour", "Potatoes", "Peas", "Spices"],
      rating: 4.6,
      category: "Snacks",
      image: "samosa.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Crunchy and delicious!", "Best with chai."],
    },
    {
      _id: "12",
      name: "Gulab Jamun",
      price: 90,
      description: "Soft and spongy milk-solid balls soaked in sugar syrup.",
      ingredients: ["Milk Solids", "Sugar", "Rose Water", "Cardamom"],
      rating: 4.8,
      category: "Dessert",
      image: "gulab_jamun.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Sweet and soft!", "Perfect dessert."],
    },
    {
      _id: "13",
      name: "Rasgulla",
      price: 100,
      description: "Spongy cheese balls soaked in sugar syrup.",
      ingredients: ["Chhena", "Sugar", "Water", "Cardamom"],
      rating: 4.7,
      category: "Dessert",
      image: "rasgulla.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Melts in the mouth!", "Perfect sweetness."],
    },
    {
      _id: "14",
      name: "Pani Puri",
      price: 80,
      description:
        "Crispy puris filled with tangy, spicy water and potato stuffing.",
      ingredients: ["Flour", "Potatoes", "Tamarind", "Mint", "Spices"],
      rating: 4.9,
      category: "Street Food",
      image: "pani_puri.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Best street food ever!", "Crispy and flavorful."],
    },
    {
      _id: "15",
      name: "Butter Naan",
      price: 70,
      description: "Soft, buttery leavened bread cooked in a tandoor.",
      ingredients: ["Flour", "Yeast", "Butter", "Salt"],
      rating: 4.7,
      category: "Bread",
      image: "butter_naan.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Soft and fluffy!", "Perfect with curries."],
    },
    {
      _id: "16",
      name: "Palak Paneer",
      price: 330,
      description: "Cottage cheese cooked in a creamy spinach gravy.",
      ingredients: ["Paneer", "Spinach", "Cream", "Spices"],
      rating: 4.8,
      category: "Curry",
      image: "palak_paneer.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Healthy and tasty!", "Smooth texture."],
    },
    {
      _id: "17",
      name: "Pav Bhaji",
      price: 200,
      description: "Spicy mashed vegetable curry served with buttered buns.",
      ingredients: ["Potatoes", "Tomatoes", "Peas", "Spices", "Butter"],
      rating: 4.9,
      category: "Street Food",
      image: "pav_bhaji.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Best street food!", "Spicy and buttery."],
    },
    {
      _id: "18",
      name: "Dhokla",
      price: 150,
      description: "Steamed gram flour snack, light and fluffy.",
      ingredients: ["Gram Flour", "Yogurt", "Mustard Seeds", "Turmeric"],
      rating: 4.7,
      category: "Snacks",
      image: "dhokla.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Soft and spongy!", "Perfect tea-time snack."],
    },
    {
      _id: "19",
      name: "Malai Kofta",
      price: 360,
      description:
        "Dumplings made of paneer and potatoes in a rich tomato gravy.",
      ingredients: ["Paneer", "Potatoes", "Tomato", "Cashew Paste"],
      rating: 4.8,
      category: "Curry",
      image: "malai_kofta.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": [
        "Creamy and delicious!",
        "Perfect for special occasions.",
      ],
    },
    {
      _id: "20",
      name: "Kadhai Chicken",
      price: 490,
      description:
        "Spicy chicken dish cooked in a kadhai with capsicum and onions.",
      ingredients: ["Chicken", "Onions", "Capsicum", "Spices"],
      rating: 4.8,
      category: "Curry",
      image: "kadhai_chicken.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": ["Spicy and flavorful!", "Loved the masala."],
    },
    {
      _id: "21",
      name: "Rava Idli",
      price: 140,
      description:
        "Soft, steamed semolina cakes served with chutney and sambar.",
      ingredients: ["Semolina", "Yogurt", "Mustard Seeds", "Curry Leaves"],
      rating: 4.6,
      category: "South Indian",
      image: "rava_idli.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": [
        "Healthy and light!",
        "Tastes great with coconut chutney.",
      ],
    },
    {
      _id: "22",
      name: "Mutton Keema",
      price: 520,
      description: "Minced mutton cooked with aromatic spices and peas.",
      ingredients: ["Mutton", "Peas", "Onions", "Spices"],
      rating: 4.9,
      category: "Non-Veg",
      image: "mutton_keema.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": ["Juicy and delicious!", "Perfect with pav."],
    },
    {
      _id: "23",
      name: "Fish Curry",
      price: 450,
      description: "Tangy and spicy fish curry with coconut and tamarind.",
      ingredients: ["Fish", "Coconut Milk", "Tamarind", "Spices"],
      rating: 4.8,
      category: "Curry",
      image: "fish_curry.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": [
        "Authentic coastal taste!",
        "Loved the coconut flavor.",
      ],
    },
    {
      _id: "24",
      name: "Shahi Tukda",
      price: 170,
      description: "Fried bread soaked in saffron-infused sweetened milk.",
      ingredients: ["Bread", "Milk", "Sugar", "Saffron"],
      rating: 4.7,
      category: "Dessert",
      image: "shahi_tukda.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Royal and delicious!", "Rich taste."],
    },
    {
      _id: "25",
      name: "Bhindi Masala",
      price: 250,
      description: "Stir-fried okra with onions and spices.",
      ingredients: ["Okra", "Onions", "Tomatoes", "Spices"],
      rating: 4.6,
      category: "Curry",
      image: "bhindi_masala.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Healthy and tasty!", "Perfect homely food."],
    },
    {
      _id: "26",
      name: "Gajar Ka Halwa",
      price: 190,
      description: "Slow-cooked carrot dessert with milk and dry fruits.",
      ingredients: ["Carrots", "Milk", "Sugar", "Dry Fruits"],
      rating: 4.9,
      category: "Dessert",
      image: "gajar_ka_halwa.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Rich and delicious!", "Perfect winter dessert."],
    },
    {
      _id: "27",
      name: "Egg Curry",
      price: 280,
      description: "Boiled eggs simmered in a flavorful onion-tomato gravy.",
      ingredients: ["Eggs", "Tomatoes", "Onions", "Spices"],
      rating: 4.7,
      category: "Curry",
      image: "egg_curry.jpg",
      "veg/non-veg": "Non-Veg",
      "customer reviews": ["Spicy and rich!", "Tastes great with rice."],
    },
    {
      _id: "28",
      name: "Misal Pav",
      price: 180,
      description: "Spicy sprouted lentil curry served with pav and farsan.",
      ingredients: ["Sprouts", "Onions", "Spices", "Pav"],
      rating: 4.8,
      category: "Street Food",
      image: "misal_pav.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": [
        "Super spicy and tasty!",
        "Authentic Maharashtra taste.",
      ],
    },
    {
      _id: "29",
      name: "Veg Pulao",
      price: 240,
      description: "Fragrant rice cooked with vegetables and whole spices.",
      ingredients: ["Basmati Rice", "Carrots", "Peas", "Spices"],
      rating: 4.6,
      category: "Rice",
      image: "veg_pulao.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Simple and tasty!", "Perfect with raita."],
    },
    {
      _id: "30",
      name: "Baingan Bharta",
      price: 260,
      description: "Smoky mashed eggplant cooked with onions and spices.",
      ingredients: ["Eggplant", "Onions", "Tomatoes", "Spices"],
      rating: 4.6,
      category: "Curry",
      image: "baingan_bharta.jpg",
      "veg/non-veg": "Veg",
      "customer reviews": ["Smoky and flavorful!", "Perfect with roti."],
    },
  ],
};
